#spring:
#  datasource:
#     url: jdbc:sqlserver://shoe.database.windows.net:1433;database=shoe;user=Twist1154@shoe;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
#    username: Rethabile@shoeserver
#    password: Ntsekhe12
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.SQLServer2016Dialect
#
# Server Configuration
#    server:
#    servlet:
#     context-path: /store
